services:
  portfolio:
    build:
      context: ./
      dockerfile: ./src/dockerfiles/Dockerfile.prod
    container_name: portfolio
    ports:
      - "80:80"
    volumes:
      - .:/portfolio
      - /portfolio/node_modules
    restart: always